# Generated by Django 3.2.8 on 2021-11-06 16:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='measurements.measurement')),
                ('systolic', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(190)])),
                ('diastolic', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(120)])),
                ('pulse', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)])),
            ],
            bases=('measurements.measurement',),
        ),
        migrations.CreateModel(
            name='Sugar',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='measurements.measurement')),
                ('level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)])),
            ],
            bases=('measurements.measurement',),
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('measurement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='measurements.measurement')),
                ('weight_value', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)])),
            ],
            bases=('measurements.measurement',),
        ),
    ]
