# Generated by Django 3.2.8 on 2022-01-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220120_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='measurement_minutes',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
